application: noblepathsfwd
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

# bootstrip url links
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /images/(.*\.(gif|png|jpg))
  static_files: images/\1
  upload: images/(.*\.(gif|png|jpg))



- url: /.*
  script: main.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest